[tool.black]
line-length = 120
target-version = ["py39"]
include = '\.pyi?$'

[tool.ruff]
line-length = 120
target-version = "py39"

# Enable rules
select = [
    "E",    # pycodestyle errors
    "F",    # pyflakes errors
    "B",    # flake8-bugbear
    "I",    # isort
]
ignore = []

[tool.ruff.isort]
combine-as-imports = true
force-sort-within-sections = true

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = false
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
show_error_codes = true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false